repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-toml
      - id: check-yaml
        args: ["--unsafe"]
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: .+\.csv
      - id: mixed-line-ending
        args: [--fix=lf]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.6
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: local
    hooks:
      - id: ruff-sort-imports
        name: ruff-sort-imports
        entry: poetry run ruff check --select I .
        language: system
        pass_filenames: false
        types: [python]
